### ISSUE TITLE
UnboundLocalError: local variable 'success' referenced before assignment

### ISSUE THREAD

**Issue by leopucci-zz** [PhilRW/gcontacts-asterisk#4]
./contatosleo.py --noauth_local_webserver                          Traceback (most recent call last):
  File "./contatosleo.py", line 224, in <module>
    main()
  File "./contatosleo.py", line 129, in main
    token = get_auth_token()
  File "./contatosleo.py", line 110, in get_auth_token
    credentials = tools.run_flow(flow, storage, args)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 180, in run_flow
    if not success:
UnboundLocalError: local variable 'success' referenced before assignment

**Comment by leopucci-zz** [comment]
https://github.com/google/oauth2client/issues/303

The problem appears in oauth2client\tools.py line 167. success = False needs to be moved up above this statement: if not flags.noauth_local_webserver: to line 166. Problem solved.

**Comment by PhilRW** [comment]
Is there a change request somewhere in here or is this strictly informational?

**Comment by leopucci-zz** [comment]
Just informational, more people will have this problem. Usually i try to find the solution on the issues list on the project, so i am writing on it. 

This is oauth2client related. pip install version does not have the latest fixes for now!

**Comment by PhilRW** [comment]
Closing because no action to take.
