### ISSUE TITLE
TypeError: decoding Unicode is not supported

### ISSUE THREAD

**Issue by leopucci-zz** [PhilRW/gcontacts-asterisk#5]
File "./contatosleo.py", line 178, in main
    phone.text = unicode(phone.text, 'utf8')
TypeError: decoding Unicode is not supported

**Comment by leopucci** [comment]
Might be this line that is giving trouble
asterisk -rx 'database put cidname 019981383089 "Märcinhü"'

**Comment by leopucci-zz** [comment]
I think that the problem is with unicode chars not being convertet do utf8. 
This might be a solution, but as i don´t know how to ident python on vim, will not give a shot...
http://stackoverflow.com/questions/20078816/replace-non-ascii-characters-with-a-single-space

If someone can add a filter, I can try it here to see if it is fixed

**Comment by leopucci-zz** [comment]
http://stackoverflow.com/questions/3857763/decoding-if-its-not-unicode

When you take a unicode object and call its decode method with the 'utf-8' codec, Python first tries to convert the unicode object to a string object, and then it calls the string object's decode('utf-8') method.

Sometimes the conversion from unicode object to string object fails because Python2 uses the ascii codec by default.

So, in general, never try to decode unicode objects. Or, if you must try, trap it in a try..except block. There may be a few codecs for which decoding unicode objects works in Python2 (see below), but they have been removed in Python3.

**Comment by PhilRW** [comment]
Was this not solved by #2?

**Comment by leopucci-zz** [comment]
Nice! Let me try. 
Well.. no donut either!

root@arm:/etc/asterisk/googleapi# ./contatosleo.py --ascii
asterisk -rx 'database put cidname 019982383089 "Marcinho Motta"'
asterisk -rx 'database put cidname 011975021366 "Silas"'
asterisk -rx 'database put cidname 011975021366 "Silas"'
Traceback (most recent call last):
  File "./contatosleo.py", line 224, in <module>
    main()
  File "./contatosleo.py", line 178, in main
    phone.text = unicode(phone.text, 'utf8')
TypeError: decoding Unicode is not supported

**Comment by leopucci-zz** [comment]
Maybe this is related to some null position and not utf8, how do you debug?
i can try again and print a stack trace so we could analize

**Comment by PhilRW** [comment]
Try checking out branch `issue-5` and see if that fixes the problem.

**Comment by leopucci-zz** [comment]
@PhilRW, did not solved. 

Problem seems to be related to "+"

011 97502-1266
asterisk -rx 'database put cidname 011975021564 "Name"'
+1 (224) 315-3621‬
Traceback (most recent call last):
  File "./contatosleo.py", line 236, in <module>
    main()
  File "./contatosleo.py", line 184, in main
    phone.text = unicode(phone.text, 'utf8')

**Comment by PhilRW** [comment]
Try it now, I've changed the UTF-8 encoding method.

**Comment by leopucci-zz** [comment]
Solved!

But now i am having another error:
ERROR: The following entry has no way to determine a name:
Please fix or remove this entry and re-run the script.

Why an error? We could just ignore the contact. 

I have changed the:

print "Please fix or remove this entry and re-run the script."
                exit(1)

TO:

print "Please fix or remove this entry and re-run the script."
                break

and now seems more reasonable, my acount have several e-mail addresses without a number. 

If you need any hard test you can count on me, lol :8ball:

**Comment by PhilRW** [comment]
I initially thought that might be the reason why you were getting the error. I'm uploading a new version that sends the errors to stderr, please test to see if it works properly.

**Comment by leopucci-zz** [comment]
Worked Perfectly!
FLAWLESS VICTORY! :100: 

![image](http://pagesdigital.pagesdigital.netdna-cdn.com/wp-content/uploads/2014/05/FLAWLESS-VICTORY.gif)
